<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="${tf_prefix}rhr_flex_model">

	<xacro:arg name="attached" default="true"/>

	<xacro:property name="has_parent" value="$(arg attached)"/>

<!-- ################ ################ ################ ################ ################ ################ -->
<!-- ################ XACRO PORTION OF THE URDF, FOR MAKING THE FLEXIBLE JOINTS ################ -->
<!-- ################ ################ ################ ################ ################ ################ -->

	<xacro:property name="flex_length" value="0.016" />
	<xacro:property name="num_steps" value="9" />
	<xacro:property name="prox_length" value="0.060" />
	<xacro:property name="pi" value="3.1415" />

 	<xacro:macro name="base_color">
 		<color rgba="0.1 0.1 0.1 1"/>
 	</xacro:macro>

 	<xacro:macro name="swivel_color">
 		<color rgba="0.1 0.1 0.1 1"/>
 	</xacro:macro>

 	<xacro:macro name="proximal_color">
 		<color rgba="0.16 0.16 0.16 1"/>
 	</xacro:macro>

 	 <xacro:macro name="distal_color">
 		<color rgba="0.16 0.16 0.16 1"/>
 	</xacro:macro>

 	<xacro:macro name="flex_color">
 		<color rgba="0.2 0.2 .2 1"/>
 	</xacro:macro>

  <xacro:macro name="pad_color">
    <color rgba="0.106 0.227 0.631 1"/>
  </xacro:macro>

  <!-- Macro to make each part of the link -->
  <xacro:macro name="flex_link" params="finger_id flex_id">
    <link
      name="${tf_prefix}finger[${finger_id}]/flex_link[${flex_id}]">
      <visual>
        <origin
          xyz="0.001 -0.007 0.003"
          rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh
            filename="package://reflex_visualizer/meshes/flex_block.STL" />
        </geometry>
        <material
          name="${tf_prefix}">
          <xacro:flex_color/>
        </material>
      </visual>
    </link>
  </xacro:macro>

	<!-- Macro to one flex body link to the next -->
	<xacro:macro name="flex_joint" params="finger_id link_parent link_child">
		<joint name="${tf_prefix}finger[${finger_id}]/flex_joint_from_${link_parent}_to_${link_child}" type="continuous">
			<parent link="${tf_prefix}finger[${finger_id}]/flex_link[${link_parent}]"/>
			<child link="${tf_prefix}finger[${finger_id}]/flex_link[${link_child}]"/>
			<origin xyz="${flex_length/num_steps} 0 0" />
			<axis xyz="0 -1 0"/>
		</joint>
	</xacro:macro>

	<!-- Macro to make the joint from proximal to first link and from last link to distal  -->
	<xacro:macro name="flex_to_segment_joint" params="finger_id">
		<joint name="${tf_prefix}finger[${finger_id}]/flex_joint_from_prox_to_1" type="continuous">
			<parent link="${tf_prefix}proximal_${finger_id}"/>
			<child link="${tf_prefix}finger[${finger_id}]/flex_link[1]"/>
			<origin xyz="${prox_length} 0 -0.004"/>
			<axis xyz="0 -1 0"/>
		</joint>

		<joint name="${tf_prefix}finger[${finger_id}]/flex_joint_from_${num_steps}_to_dist" type="continuous">
			<parent link="${tf_prefix}finger[${finger_id}]/flex_link[${num_steps}]"/>
			<child link="${tf_prefix}distal_${finger_id}"/>
			<origin xyz="${flex_length/num_steps-0.01} 0 0.008"/>
			<axis xyz="0 -1 0"/>
		</joint>
	</xacro:macro>

	<xacro:macro name="reflex_xacro" params="tf_prefix='' parent='' twist=0">

		<xacro:flex_link finger_id="1" flex_id="1"/>
	  <xacro:flex_link finger_id="1" flex_id="2"/>
	  <xacro:flex_link finger_id="1" flex_id="3"/>
		<xacro:flex_link finger_id="1" flex_id="4"/>
	  <xacro:flex_link finger_id="1" flex_id="5"/>
	  <xacro:flex_link finger_id="1" flex_id="6"/>
	 	<xacro:flex_link finger_id="1" flex_id="7"/>
	  <xacro:flex_link finger_id="1" flex_id="8"/>
	  <xacro:flex_link finger_id="1" flex_id="9"/>
		<xacro:flex_joint finger_id="1" link_parent="1" link_child="2"/>
	  <xacro:flex_joint finger_id="1" link_parent="2" link_child="3"/>
		<xacro:flex_joint finger_id="1" link_parent="3" link_child="4"/>
	  <xacro:flex_joint finger_id="1" link_parent="4" link_child="5"/>
		<xacro:flex_joint finger_id="1" link_parent="5" link_child="6"/>
	  <xacro:flex_joint finger_id="1" link_parent="6" link_child="7"/>
		<xacro:flex_joint finger_id="1" link_parent="7" link_child="8"/>
	  <xacro:flex_joint finger_id="1" link_parent="8" link_child="9"/>
	 	<xacro:flex_to_segment_joint finger_id="1"/>

		<xacro:flex_link finger_id="2" flex_id="1"/>
	  <xacro:flex_link finger_id="2" flex_id="2"/>
	  <xacro:flex_link finger_id="2" flex_id="3"/>
		<xacro:flex_link finger_id="2" flex_id="4"/>
	  <xacro:flex_link finger_id="2" flex_id="5"/>
	  <xacro:flex_link finger_id="2" flex_id="6"/>
	 	<xacro:flex_link finger_id="2" flex_id="7"/>
	  <xacro:flex_link finger_id="2" flex_id="8"/>
	  <xacro:flex_link finger_id="2" flex_id="9"/>
		<xacro:flex_joint finger_id="2" link_parent="1" link_child="2"/>
	  <xacro:flex_joint finger_id="2" link_parent="2" link_child="3"/>
		<xacro:flex_joint finger_id="2" link_parent="3" link_child="4"/>
	  <xacro:flex_joint finger_id="2" link_parent="4" link_child="5"/>
		<xacro:flex_joint finger_id="2" link_parent="5" link_child="6"/>
	  <xacro:flex_joint finger_id="2" link_parent="6" link_child="7"/>
		<xacro:flex_joint finger_id="2" link_parent="7" link_child="8"/>
	  <xacro:flex_joint finger_id="2" link_parent="8" link_child="9"/>
	 	<xacro:flex_to_segment_joint finger_id="2"/>

		<xacro:flex_link finger_id="3" flex_id="1"/>
	  <xacro:flex_link finger_id="3" flex_id="2"/>
	  <xacro:flex_link finger_id="3" flex_id="3"/>
		<xacro:flex_link finger_id="3" flex_id="4"/>
	  <xacro:flex_link finger_id="3" flex_id="5"/>
	  <xacro:flex_link finger_id="3" flex_id="6"/>
	 	<xacro:flex_link finger_id="3" flex_id="7"/>
	  <xacro:flex_link finger_id="3" flex_id="8"/>
	  <xacro:flex_link finger_id="3" flex_id="9"/>
		<xacro:flex_joint finger_id="3" link_parent="1" link_child="2"/>
	  <xacro:flex_joint finger_id="3" link_parent="2" link_child="3"/>
		<xacro:flex_joint finger_id="3" link_parent="3" link_child="4"/>
	  <xacro:flex_joint finger_id="3" link_parent="4" link_child="5"/>
		<xacro:flex_joint finger_id="3" link_parent="5" link_child="6"/>
	  <xacro:flex_joint finger_id="3" link_parent="6" link_child="7"/>
		<xacro:flex_joint finger_id="3" link_parent="7" link_child="8"/>
	  <xacro:flex_joint finger_id="3" link_parent="8" link_child="9"/>
	 	<xacro:flex_to_segment_joint finger_id="3"/>



		<xacro:if value="${has_parent}">
			<joint name="${tf_prefix}to_hand_joint" type="fixed">
				<origin rpy="0 0 ${twist}" xyz="0 0 0"/>
				<parent link="${parent}"/>
				<child link="${tf_prefix}hand_base"/>
			</joint>
		</xacro:if>


<!-- ################ ################ ################ ################ ################ ################ -->
<!-- ################ THE SECTION CREATED BY SOLIDWORKS EXPORTER, CUT AND PASTE THIS IN HERE ################ -->
<!-- ################ YOU CAN ALTER THE COLORS FROM HERE ################ -->
<!-- ################ COMMENT OUT ALL dist*_joint PIECES OF THIS URDF SO THE FLEX JOINTS CAN LINK UP ################ -->
<!-- ################ ################ ################ ################ ################ ################ -->
	  <link
	    name="${tf_prefix}hand_base">
	    <visual>
	      <origin
	        xyz="0 0 0"
	        rpy="0 0 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/base_link.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:base_color/>
	      </material>
	    </visual>
	  </link>
	  <link
	    name="${tf_prefix}pad">
	    <visual>
	      <origin
	        xyz="0 0 0"
	        rpy="0 0 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/pad.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:pad_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}pad_joint"
	    type="fixed">
	    <origin
	      xyz="0.02 0 0.063"
	      rpy="1.5707963267949 5.55111512312578E-17 -1.5707963267949" />
	    <parent
	      link="${tf_prefix}hand_base" />
	    <child
	      link="${tf_prefix}pad" />
	    <axis
	      xyz="0 0 0" />
	  </joint>
	  <link
	    name="${tf_prefix}swivel_1">
	    <visual>
	      <origin
	        xyz="0 0 0"
	        rpy="0 0 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/swivel_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:swivel_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}preshape_1"
	    type="continuous">
	    <origin
	      xyz="0.0503973683071414 -0.026 0.063"
	      rpy="6.75550818663469E-16 1.97993848419069E-16 -2.77555756156289E-16" />
	    <parent
	      link="${tf_prefix}hand_base" />
	    <child
	      link="${tf_prefix}swivel_1" />
	    <axis
	      xyz="0 0 -1" />
	  </joint>
	  <link
	    name="${tf_prefix}proximal_1">
	    <visual>
	      <origin
	        xyz="-0.011 0.007 0.011"
	        rpy="3.1459 0 0"/>
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/proximal_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:proximal_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}proximal_joint_1"
	    type="continuous">
	    <origin
	      xyz="0.01 0 0.0186"
	      rpy="-6.20039667432211E-16 0 2.22044604925031E-16" />
	    <parent
	      link="${tf_prefix}swivel_1" />
	    <child
	      link="${tf_prefix}proximal_1" />
	    <axis
	      xyz="0 -1 0" />
	  </joint>
	  <link
	    name="${tf_prefix}proximal_pad_1">
	    <visual>
	      <origin
	        xyz="-0.008 0.014 -0.002"
	        rpy="1.5708 1.5708 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/proximal_pad_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:pad_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}prox1_pad_joint"
	    type="fixed">
	    <origin
	      xyz="0 0 0"
	      rpy="1.5707963267949 0 -1.5707963267949" />
	    <parent
	      link="${tf_prefix}proximal_1" />
	    <child
	      link="${tf_prefix}proximal_pad_1" />
	    <axis
	      xyz="0 0 0" />
	  </joint>
	  <link
	    name="${tf_prefix}distal_1">
	    <visual>
	      <origin
	        xyz="-0.077 0.007 0.007"
	        rpy="3.1459 0 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/distal_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:distal_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}distal_joint_1"
	    type="continuous">
	    <origin
	      xyz="0.07600000000000001 0 0.00250000000000002"
	      rpy="0 0 0" />
	    <parent
	      link="${tf_prefix}proximal_1" />
	    <child
	      link="${tf_prefix}distal_1" />
	    <axis
	      xyz="0 -1 0" />
	  </joint>
	  <link
	    name="${tf_prefix}distal_pad_1">
	    <visual>
	      <origin
	        xyz="-0.00825 0.009 0.057"
	        rpy="1.5708 1.5708 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/distal_pad_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:pad_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}dist1_pad_joint"
	    type="fixed">
	    <origin
	      xyz="-0.01 0 0.001"
	      rpy="1.5707963267949 0 -1.5707963267949" />
	    <parent
	      link="${tf_prefix}distal_1" />
	    <child
	      link="${tf_prefix}distal_pad_1" />
	    <axis
	      xyz="0 0 0" />
	  </joint>
	  <link
	    name="${tf_prefix}swivel_2">
	    <visual>
	      <origin
	        xyz="0 0 0"
	        rpy="0 0 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/swivel_2.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:swivel_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}preshape_2"
	    type="continuous">
	    <origin
	      xyz="0.0503973683071413 0.0259999999999999 0.063"
	      rpy="1.22459340959228E-15 -7.33448407631817E-16 -1.66533453693773E-16" />
	    <parent
	      link="${tf_prefix}hand_base" />
	    <child
	      link="${tf_prefix}swivel_2" />
	    <axis
	      xyz="0 0 -1" />
	  </joint>
	  <link
	    name="${tf_prefix}proximal_2">
	    <visual>
	      <origin
	        xyz="-0.011 0.007 0.011"
	        rpy="3.1459 0 0"/>
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/proximal_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:proximal_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}proximal_joint_2"
	    type="continuous">
	    <origin
	      xyz="0.01 0 0.0186"
	      rpy="-1.16908225836102E-15 0 1.11022302462515E-16" />
	    <parent
	      link="${tf_prefix}swivel_2" />
	    <child
	      link="${tf_prefix}proximal_2" />
	    <axis
	      xyz="0 -1 0" />
	  </joint>
	  <link
	    name="${tf_prefix}proximal_pad_2">
	    <visual>
	      <origin
	        xyz="-0.008 0.014 -0.002"
	        rpy="1.5708 1.5708 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/proximal_pad_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:pad_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}prox2_pad_joint"
	    type="fixed">
	    <origin
	      xyz="0 0 0"
	      rpy="1.5707963267949 0 -1.5707963267949" />
	    <parent
	      link="${tf_prefix}proximal_2" />
	    <child
	      link="${tf_prefix}proximal_pad_2" />
	    <axis
	      xyz="0 0 0" />
	  </joint>
	  <link
	    name="${tf_prefix}distal_2">
	    <visual>
	      <origin
	        xyz="-0.077 0.007 0.006"
	        rpy="3.1459 0 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/distal_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:distal_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}distal_joint_2"
	    type="continuous">
	    <origin
	      xyz="0.0760000000000001 0 0.00249999999999997"
	      rpy="0 0 0" />
	    <parent
	      link="${tf_prefix}proximal_2" />
	    <child
	      link="${tf_prefix}distal_2" />
	    <axis
	      xyz="0 -1 0" />
	  </joint>
	  <link
	    name="${tf_prefix}distal_pad_2">
	    <visual>
	      <origin
	        xyz="-0.00825 0.009 0.057"
	        rpy="1.5708 1.5708 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/distal_pad_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:pad_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}dist2_pad_joint"
	    type="fixed">
	    <origin
	      xyz="-0.01 0 0.001"
	      rpy="1.5707963267949 0 -1.5707963267949" />
	    <parent
	      link="${tf_prefix}distal_2" />
	    <child
	      link="${tf_prefix}distal_pad_2" />
	    <axis
	      xyz="0 0 0" />
	  </joint>
	  <link
	    name="${tf_prefix}proximal_3">
	    <visual>
	      <origin
	        xyz="-0.011 0.007 0.011"
	        rpy="3.1459 0 0"/>
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/proximal_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:proximal_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}proximal_joint_3"
	    type="continuous">
	    <origin
	      xyz="-0.0299999999999996 0 0.0816000000000002"
	      rpy="-5.55111512312578E-17 0 3.14159265358979" />
	    <parent
	      link="${tf_prefix}hand_base" />
	    <child
	      link="${tf_prefix}proximal_3" />
	    <axis
	      xyz="0 -1 0" />
	  </joint>
	  <link
	    name="${tf_prefix}proximal_pad_3">
	    <visual>
	      <origin
	        xyz="-0.008 0.014 -0.002"
	        rpy="1.5708 1.5708 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/proximal_pad_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:pad_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}prox3_pad_joint"
	    type="fixed">
	    <origin
	      xyz="0 0 0"
	      rpy="1.5707963267949 1.22460635382238E-16 -1.5707963267949" />
	    <parent
	      link="${tf_prefix}proximal_3" />
	    <child
	      link="${tf_prefix}proximal_pad_3" />
	    <axis
	      xyz="0 0 0" />
	  </joint>
	  <link
	    name="${tf_prefix}distal_3">
	    <visual>
	      <origin
	        xyz="-0.077 0.007 0.006"
	        rpy="3.1459 0 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/distal_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:distal_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}distal_joint_3"
	    type="continuous">
	    <origin
	      xyz="0.0760000000000001 0 0.0025"
	      rpy="-1.48887961834512E-45 -1.0995850059156E-76 -7.38531841236285E-32" />
	    <parent
	      link="${tf_prefix}proximal_3" />
	    <child
	      link="${tf_prefix}distal_3" />
	    <axis
	      xyz="0 -1 0" />
	  </joint>
	  <link
	    name="${tf_prefix}distal_pad_3">
	    <visual>
	      <origin
	        xyz="-0.00825 0.009 0.057"
	        rpy="1.5708 1.5708 0" />
	      <geometry>
	        <mesh
	          filename="package://reflex_visualizer/meshes/distal_pad_1.STL" />
	      </geometry>
	      <material
	        name="${tf_prefix}">
	        <xacro:pad_color/>
	      </material>
	    </visual>
	  </link>
	  <joint
	    name="${tf_prefix}dist3_pad_joint"
	    type="fixed">
	    <origin
	      xyz="-0.01 0 0.001"
	      rpy="1.5707963267949 0 -1.5707963267949" />
	    <parent
	      link="${tf_prefix}distal_3" />
	    <child
	      link="${tf_prefix}distal_pad_3" />
	    <axis
	      xyz="0 0 0" />
	  </joint>









	<!-- ################ ################ ################ ################ ################ ################ -->
	<!-- ################ THIS SECTION LINKS THE MARKERS (TACTILE DATA) TO THE CAD MESH ################ -->
	<!-- ################ COPY AND PASTE THIS FROM urdf/homemade_marker_portion_urdf  ################ -->
	<!-- ################ ################ ################ ################ ################ ################ -->

	  <joint name="${tf_prefix}base_tactile_joint" type="fixed">
	    <origin xyz="0 0 0" rpy="0 0 0" />
	    <parent link="${tf_prefix}hand_base" />
	    <child link="${tf_prefix}base_tactile" />
	  </joint>

	  <link name="${tf_prefix}base_tactile"/>

	  <link name="${tf_prefix}proximal_1_tactile" />

	  <joint name="${tf_prefix}proximal_1_tactile_joint" type="fixed">
	    <origin xyz="0 0 0" rpy="0 0 0" />
	    <parent link="${tf_prefix}proximal_1" />
	    <child link="${tf_prefix}proximal_1_tactile" />
	  </joint>

	  <joint name="${tf_prefix}proximal_2_tactile_joint" type="fixed">
	    <origin xyz="0 0 0" rpy="0 0 0" />
	    <parent link="${tf_prefix}proximal_2" />
	    <child link="${tf_prefix}proximal_2_tactile" />
	  </joint>

	  <link name="${tf_prefix}proximal_2_tactile"/>

	  <joint name="${tf_prefix}proximal_3_tactile_joint" type="fixed">
	    <origin xyz="0 0 0" rpy="0 0 0" />
	    <parent link="${tf_prefix}proximal_3" />
	    <child link="${tf_prefix}proximal_3_tactile" />
	  </joint>

	  <link name="${tf_prefix}proximal_3_tactile"/>

	  <joint name="${tf_prefix}distal_1_tactile_joint" type="fixed">
	    <origin xyz="-0.0062 0 0" rpy="0 0 0" />
	    <parent link="${tf_prefix}distal_1" />
	    <child link="${tf_prefix}distal_1_tactile" />
	  </joint>

	  <link name="${tf_prefix}distal_1_tactile"/>

	  <joint name="${tf_prefix}distal_2_tactile_joint" type="fixed">
	    <origin xyz="-0.0062 0 0" rpy="0 0 0" />
	    <parent link="${tf_prefix}distal_2" />
	    <child link="${tf_prefix}distal_2_tactile" />
	  </joint>

	  <link name="${tf_prefix}distal_2_tactile"/>

	  <joint name="${tf_prefix}distal_3_tactile_joint" type="fixed">
	    <origin xyz="-0.0062 0 0" rpy="0 0 0" />
	    <parent link="${tf_prefix}distal_3" />
	    <child link="${tf_prefix}distal_3_tactile" />
	  </joint>

	  <link name="${tf_prefix}distal_3_tactile"/>
</xacro:macro>
</robot>
